---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.16.2

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[nix::default]
    attributes:
