---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.19.36

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[nix::default]
    attributes:
